export const translations = {
  en: {
    appName: 'Nawerni',
    appSlogan: 'Track, donate, never waste',
    notifications: 'Notifications',
    enableNotifications: 'Enable browser notifications to get expiry alerts',
    enableBtn: 'Enable Notifications',
    notificationsBlocked: '❌ Notifications blocked. Please allow them in your browser settings.',
    noExpiring: '✅ No items expiring soon!',
    totalItems: 'Total Items',
    expiringSoon: 'Expiring Soon',
    within14: 'Within 14 days',
    medicine: 'Medicine',
    food: 'Food',
    quickActions: 'Quick Actions',
    scanItem: 'Scan Item',
    addWithCamera: 'Add with camera',
    findDonation: 'Find Donation',
    nearbyCenters: 'Nearby centers',
    recentItems: 'Recent Items',
    noItems: 'No items yet. Add your first item!',
    expiringSoonAlert: 'expiring soon!',
    expiresIn: 'Expires in',
    days: 'days',
    considerDonating: 'consider using or donating',
    dashboard: 'Dashboard',
    inventory: 'Inventory',
    scan: 'Scan',
    donate: 'Donate',
    analytics: 'Analytics',
    addItem: 'Add Item',
    simulateScan: 'Simulate Scan',
    openCamera: '📷 Open Camera',
    closeCamera: '✕ Close Camera',
    orAddManually: '— or add manually —',
    productName: 'Product Name',
    productPlaceholder: 'e.g. Milk, Paracetamol',
    category: 'Category',
    foodCat: 'Food',
    medicineCat: 'Medicine',
    otherCat: 'Other',
    expiryDate: 'Expiry Date',
    quantity: 'Quantity',
    nearbyDonation: 'Nearby Donation Centers',
    riyadh: 'Riyadh, Saudi Arabia',
    donationCentersNear: 'Donation Centers Near You',
    navigate: '📍 Navigate',
    accepts: 'Accepts',
    removeItem: 'Remove',
    dLeft: 'd left',
    expired: 'Expired',
    profile: 'Profile',
  },
  ar: {
    appName: 'نوِّرني',
    appSlogan: 'تتبع، تبرع، لا تهدر',
    notifications: 'الإشعارات',
    enableNotifications: 'فعّل إشعارات المتصفح لتلقي تنبيهات انتهاء الصلاحية',
    enableBtn: 'تفعيل الإشعارات',
    notificationsBlocked: '❌ الإشعارات محظورة. يرجى السماح بها في إعدادات المتصفح.',
    noExpiring: '✅ لا توجد منتجات تنتهي صلاحيتها قريباً!',
    totalItems: 'إجمالي المنتجات',
    expiringSoon: 'تنتهي قريباً',
    within14: 'خلال 14 يوم',
    medicine: 'دواء',
    food: 'طعام',
    quickActions: 'إجراءات سريعة',
    scanItem: 'مسح منتج',
    addWithCamera: 'أضف بالكاميرا',
    findDonation: 'مراكز التبرع',
    nearbyCenters: 'المراكز القريبة',
    recentItems: 'المنتجات الأخيرة',
    noItems: 'لا توجد منتجات بعد. أضف أول منتج!',
    expiringSoonAlert: 'تنتهي صلاحيته قريباً!',
    expiresIn: 'تنتهي خلال',
    days: 'أيام',
    considerDonating: 'فكر في الاستخدام أو التبرع',
    dashboard: 'الرئيسية',
    inventory: 'المخزون',
    scan: 'مسح',
    donate: 'تبرع',
    analytics: 'تحليلات',
    addItem: 'إضافة منتج',
    simulateScan: 'محاكاة المسح',
    openCamera: '📷 فتح الكاميرا',
    closeCamera: '✕ إغلاق الكاميرا',
    orAddManually: '— أو أضف يدوياً —',
    productName: 'اسم المنتج',
    productPlaceholder: 'مثال: حليب، باراسيتامول',
    category: 'الفئة',
    foodCat: 'طعام',
    medicineCat: 'دواء',
    otherCat: 'أخرى',
    expiryDate: 'تاريخ الانتهاء',
    quantity: 'الكمية',
    nearbyDonation: 'مراكز التبرع القريبة',
    riyadh: 'الرياض، المملكة العربية السعودية',
    donationCentersNear: 'مراكز التبرع بالقرب منك',
    navigate: '📍 توجيه',
    accepts: 'يقبل',
    removeItem: 'حذف',
    dLeft: 'يوم متبقي',
    expired: 'منتهي',
    profile: 'الملف الشخصي',
  }
};